name: 'Run tests vs B2B-MP demoshop'

on:
  pull_request:
    types: [labeled]
  workflow_dispatch:

jobs:
  docker-php-8-2-mariadb-cypress:
    if: >
      (github.event_name == 'pull_request' && github.event.label.name == 'regression')
    name: 'Docker / PHP 8.2 / MariaDB / Cypress '
    runs-on: ubuntu-latest
    env:
      PROGRESS_TYPE: plain
      SPRYKER_PLATFORM_IMAGE: spryker/php:8.2
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Cypress
        run: npm install

      - name: Install docker-compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/2.12.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Install B2B-MP Demoshop
        run: |
          git clone -b master --single-branch https://github.com/spryker-shop/b2b-demo-marketplace.git ./b2b-mp
          git clone https://github.com/spryker/docker-sdk.git ./b2b-mp/docker
          cd b2b-mp && docker/sdk boot -v deploy.yml
          sudo bash -c "echo '127.0.0.1 backend-api.at.spryker.local backend-api.de.spryker.local glue-backend.de.spryker.local glue-backend.at.spryker.local glue-storefront.de.spryker.local glue-storefront.at.spryker.local backend-gateway.at.spryker.local backend-gateway.de.spryker.local backoffice.at.spryker.local backoffice.de.spryker.local date-time-configurator-example.spryker.local glue.at.spryker.local glue.de.spryker.local yves.at.spryker.local yves.de.spryker.local' >> /etc/hosts"
          docker/sdk up
          docker/sdk cli composer dump-autoload -o -a --apcu
          docker/sdk cli console queue:worker:start --stop-when-empty

      - name: Run Tests
        id: run_tests
        run: |
          npm run cy:run

      - name: Upload artifacts
        if: failure()
        run: echo "S3 bucket logic goes here"
